#!/usr/bin/env python3

import subprocess
from os import environ, getcwd, remove
from os.path import join
from sys import argv
import json

home_dir = environ['HOME']

PUSHLATERRC = join(home_dir, '.pushlaterrc')

def later():
    with open(PUSHLATERRC, 'a') as rc:
        rc.write('%s\n' % json.dumps({
            'cwd': getcwd(),
            'args': argv[1:]
        }))
    print('A push shall occur later. Just run "pushlater --now" when '
        'you have internets!')

def now():
    with open(PUSHLATERRC, 'r') as rc:
        for json_line in rc:
            json_line = json.loads(json_line)
            ret = subprocess.call(
                ['git', 'push'] + json_line['args'],
                cwd=json_line['cwd']
            )
            if ret:
                print('A git error has occurred.')
                print('Please cd %s and find out what happened' % json_line['cwd'])
    remove(PUSHLATERRC)

if len(argv) >= 2 and argv[1] == '--now':
    now()
else:
    later()

